/**
 * Minimal i18n — no heavy lib, just dict per locale.
 * Buyer adds locale by extending this object.
 */
export const dict = {
  en: {
    menu: "Menu",
    flavors: "Flavors",
    about: "About",
    cart: "Cart",
    checkout: "Checkout",
    total: "Total",
    addToCart: "Add to Cart",
    viewMenu: "View Menu",
    bestSeller: "Best Seller",
    new: "New",
    sold: "sold",
    stock: "Stock",
    variant: "Variant",
    placeOrder: "Place Order",
    pay: "Pay",
    orders: "Orders",
    products: "Products",
    settings: "Settings",
    logout: "Logout",
    orderSuccess: "Order placed!",
    cartEmpty: "Your cart is empty — pick a favorite flavor!",
    continueShopping: "Continue shopping",
    cartTitle: "Cart",
    emptyCart: "Cart is empty — pick a favorite flavor!",
    checkoutTitle: "Checkout",
    orderSummary: "Order Summary",
    shippingDetails: "Shipping Details",
    fullName: "Full name",
    phone: "Phone / WhatsApp",
    address: "Full address",
    notes: "Notes (optional)",
    processing: "Processing...",
    cartEmptyLink: "Shop now",
    adminOrders: "Orders",
    adminProducts: "Products",
    adminSettings: "Settings",
    adminLogout: "Logout",
    searchPlaceholder: "Search name/phone/id",
    allStatus: "All status",
    statusNew: "baru",
    statusProcessing: "diproses",
    statusCompleted: "selesai",
    statusCancelled: "batal",
    paymentPending: "pending",
    paymentPaid: "paid",
    paymentFailed: "failed",
    customerName: "Customer Name",
    customerPhone: "Phone",
    customerAddress: "Address",
    customerNotes: "Notes",
    adminAddProduct: "+ Add Product",
    adminEditProduct: "Edit Product",
    adminDeleteProduct: "Delete Product",
    adminSaveProduct: "Save",
    adminCancel: "Cancel",
    adminSaving: "Saving...",
    adminUpdate: "Update",
    adminCreate: "Create",
    adminName: "Name",
    adminSlug: "Slug",
    adminDescription: "Description",
    adminPrice: "Price",
    adminOriginalPrice: "Original price (optional)",
    adminImage: "Image URL",
    adminCategory: "Category",
    adminStock: "Stock",
    adminRating: "Rating (0-5)",
    adminBestSeller: "Best seller",
    adminNew: "New",
    adminVariants: 'Variants JSON e.g. [{"name":"1 Scoop","price":28000}]',
    adminTip: "Tip: image can be Unsplash URL. Slug must be unique.",
    settingsSiteName: "Site name",
    settingsTagline: "Tagline",
    settingsDescription: "Description (SEO)",
    settingsFooterText: "Footer text",
    settingsContactEmail: "Contact email",
    settingsSave: "Save Settings",
    settingsSaving: "Saving...",
    settingsSaved: "Settings saved — refresh to see changes",
    settingsFailed: "Failed to save",
    loginUsername: "Username",
    loginPassword: "Password",
    loginSubmit: "Login",
    loginError: "Username or password incorrect",
    loginRequired: "Username and password required",
    genericError: "An error occurred",
    homeHeroBadge: "Fresh drop • Artisan made",
    homeScrollHint: "scroll to play",
    homeFlavorJourney: "Flavor Journey",
    homeOrderFlavor: "Order this flavor",
    homeGalleryTitle: "Flavor Gallery",
    homeGallerySubtitle: "Hover to peek — flavor videos",
    homeGalleryDesc: "9 loop videos — hover to feel the motion.",
    homeBestSeller: "Best Seller",
    homeBestSellerDesc: "Vertical scroll = horizontal camera pan — like video.",
    homeCtaTitle: "Ready for something sweet?",
    homeCtaDesc: "Fast checkout — pay your way. Orders processed instantly.",
    homeOrderNow: "Order Now",
    homeAdminLogin: "Admin Login",
    headerAriaCart: "Cart",
    headerAriaMenu: "Menu",
    productDetailSold: "sold",
    productDetailStock: "Stock",
    productDetailAddToCart: "Add to Cart",
    productCardAdd: "Add",
    productCardSold: "sold",
    orderSuccessTitle: "Order Confirmed",
    orderSuccessDesc: "Your order has been placed successfully.",
    orderNumber: "Order Number",
    orderDate: "Order Date",
    orderStatus: "Status",
    orderPaymentStatus: "Payment Status",
    orderTotal: "Total",
    orderItems: "Items",
    notFound: "Page not found",
    loading: "Loading...",
  },
  id: {
    menu: "Menu",
    flavors: "Rasa",
    about: "Tentang",
    cart: "Keranjang",
    checkout: "Checkout",
    total: "Total",
    addToCart: "Tambah ke Keranjang",
    viewMenu: "Lihat Menu",
    bestSeller: "Best Seller",
    new: "Baru",
    sold: "terjual",
    stock: "Stok",
    variant: "Varian",
    placeOrder: "Buat Pesanan",
    pay: "Bayar",
    orders: "Pesanan",
    products: "Produk",
    settings: "Pengaturan",
    logout: "Keluar",
    orderSuccess: "Pesanan dibuat!",
    cartEmpty: "Keranjang kosong — ayo pilih rasa favoritmu!",
    continueShopping: "Lanjut belanja",
    cartTitle: "Keranjang",
    emptyCart: "Kosong — ayo pilih rasa favoritmu!",
    checkoutTitle: "Checkout",
    orderSummary: "Ringkasan Pesanan",
    shippingDetails: "Detail Pengiriman",
    fullName: "Nama Lengkap",
    phone: "Telepon / WhatsApp",
    address: "Alamat Lengkap",
    notes: "Catatan (opsional)",
    processing: "Memproses...",
    cartEmptyLink: "Pilih rasa dulu",
    adminOrders: "Pesanan",
    adminProducts: "Produk",
    adminSettings: "Pengaturan",
    adminLogout: "Keluar",
    searchPlaceholder: "Cari nama/telepon/id",
    allStatus: "Semua status",
    statusNew: "baru",
    statusProcessing: "diproses",
    statusCompleted: "selesai",
    statusCancelled: "batal",
    paymentPending: "pending",
    paymentPaid: "paid",
    paymentFailed: "failed",
    customerName: "Nama Pelanggan",
    customerPhone: "Telepon",
    customerAddress: "Alamat",
    customerNotes: "Catatan",
    adminAddProduct: "+ Tambah Produk",
    adminEditProduct: "Edit Produk",
    adminDeleteProduct: "Hapus Produk",
    adminSaveProduct: "Simpan",
    adminCancel: "Batal",
    adminSaving: "Menyimpan...",
    adminUpdate: "Update",
    adminCreate: "Buat",
    adminName: "Nama",
    adminSlug: "Slug",
    adminDescription: "Deskripsi",
    adminPrice: "Harga",
    adminOriginalPrice: "Harga asli (opsional)",
    adminImage: "URL Gambar",
    adminCategory: "Kategori",
    adminStock: "Stok",
    adminRating: "Rating (0-5)",
    adminBestSeller: "Best seller",
    adminNew: "Baru",
    adminVariants: 'Variants JSON e.g. [{"name":"1 Scoop","price":28000}]',
    adminTip: "Tip: gambar bisa pakai URL Unsplash. Slug harus unik.",
    settingsSiteName: "Nama toko",
    settingsTagline: "Tagline",
    settingsDescription: "Deskripsi (SEO)",
    settingsFooterText: "Teks footer",
    settingsContactEmail: "Email kontak",
    settingsSave: "Simpan Pengaturan",
    settingsSaving: "Menyimpan...",
    settingsSaved: "Pengaturan tersimpan — refresh untuk melihat perubahan",
    settingsFailed: "Gagal menyimpan",
    loginUsername: "Username",
    loginPassword: "Password",
    loginSubmit: "Masuk",
    loginError: "Username atau password salah",
    loginRequired: "Username dan password wajib diisi",
    genericError: "Terjadi kesalahan",
    homeHeroBadge: "Fresh drop • Artisan made",
    homeScrollHint: "scroll untuk play",
    homeFlavorJourney: "Jelajahi Rasa",
    homeOrderFlavor: "Pesan rasa ini",
    homeGalleryTitle: "Galeri Rasa",
    homeGallerySubtitle: "Hover untuk lihat — video rasa",
    homeGalleryDesc: "9 video loop — hover untuk merasakan gerakannya.",
    homeBestSeller: "Best Seller",
    homeBestSellerDesc: "Scroll vertikal = kamera pan horizontal — seperti video.",
    homeCtaTitle: "Siap untuk yang manis?",
    homeCtaDesc: "Checkout cepat — bayar sesuai cara kamu. Pesanan diproses instan.",
    homeOrderNow: "Pesan Sekarang",
    homeAdminLogin: "Login Admin",
    headerAriaCart: "Keranjang",
    headerAriaMenu: "Menu",
    productDetailSold: "terjual",
    productDetailStock: "Stok",
    productDetailAddToCart: "Tambah ke Keranjang",
    productCardAdd: "Tambah",
    productCardSold: "terjual",
    orderSuccessTitle: "Pesanan Dikonfirmasi",
    orderSuccessDesc: "Pesananmu berhasil dibuat.",
    orderNumber: "Nomor Pesanan",
    orderDate: "Tanggal Pesanan",
    orderStatus: "Status",
    orderPaymentStatus: "Status Pembayaran",
    orderTotal: "Total",
    orderItems: "Item",
    notFound: "Halaman tidak ditemukan",
    loading: "Memuat...",
  },
} as const

export type Locale = keyof typeof dict

export type Dict = typeof dict.en
